//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlassesOnline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBGNamCuongEntities : DbContext
    {
        public DBGNamCuongEntities()
            : base("name=DBGNamCuongEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMIN> ADMINs { get; set; }
        public DbSet<CTDONHANG> CTDONHANGs { get; set; }
        public DbSet<CTPHIEUNHAP> CTPHIEUNHAPs { get; set; }
        public DbSet<DANHGIASP> DANHGIASPs { get; set; }
        public DbSet<DONDATHANG> DONDATHANGs { get; set; }
        public DbSet<HINHTHUCGIAOHANG> HINHTHUCGIAOHANGs { get; set; }
        public DbSet<HINHTHUCTHANHTOAN> HINHTHUCTHANHTOANs { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<LOAISANPHAM> LOAISANPHAMs { get; set; }
        public DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public DbSet<PHIEUNHAP> PHIEUNHAPs { get; set; }
        public DbSet<SANPHAMGLA> SANPHAMGLAS { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
