//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlassesOnline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DBGNamCuongEntities : DbContext
    {
        public DBGNamCuongEntities()
            : base("name=DBGNamCuongEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMIN> ADMINs { get; set; }
        public DbSet<CTDonHang> CTDonHangs { get; set; }
        public DbSet<CTPHIEUNHAP> CTPHIEUNHAPs { get; set; }
        public DbSet<DANHGIASP> DANHGIASPs { get; set; }
        public DbSet<DONDATHANG> DONDATHANGs { get; set; }
        public DbSet<HINHTHUCGIAOHANG> HINHTHUCGIAOHANGs { get; set; }
        public DbSet<HINHTHUCTHANHTOAN> HINHTHUCTHANHTOANs { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<LOAISANPHAM> LOAISANPHAMs { get; set; }
        public DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public DbSet<PHIEUNHAP> PHIEUNHAPs { get; set; }
        public DbSet<SANPHAMGLA> SANPHAMGLAS { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual ObjectResult<LayDanhGia_Result> LayDanhGia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayDanhGia_Result>("LayDanhGia");
        }
    
        public virtual ObjectResult<DANHGIASP> LayDanhGiaSanPham()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DANHGIASP>("LayDanhGiaSanPham");
        }
    
        public virtual ObjectResult<DANHGIASP> LayDanhGiaSanPham(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DANHGIASP>("LayDanhGiaSanPham", mergeOption);
        }
    
        [EdmFunction("DBGNamCuongEntities", "HamLayBangDanhGia")]
        public virtual IQueryable<HamLayBangDanhGia_Result> HamLayBangDanhGia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<HamLayBangDanhGia_Result>("[DBGNamCuongEntities].[HamLayBangDanhGia]()");
        }
    }
}
