//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlassesOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public KHACHHANG()
        {
            this.DANHGIASPs = new HashSet<DANHGIASP>();
            this.DONDATHANGs = new HashSet<DONDATHANG>();
        }
    
        public int MaKH { get; set; }
        public string HoTenKH { get; set; }
        public string DiaChiKH { get; set; }
        public Nullable<int> DienThoaiKH { get; set; }
        public string TenDN { get; set; }
        public string MatKhau { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<DANHGIASP> DANHGIASPs { get; set; }
        public virtual ICollection<DONDATHANG> DONDATHANGs { get; set; }
    }
}
