//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlassesOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAMGLA
    {
        public SANPHAMGLA()
        {
            this.CTDonHangs = new HashSet<CTDonHang>();
            this.CTPHIEUNHAPs = new HashSet<CTPHIEUNHAP>();
            this.DANHGIASPs = new HashSet<DANHGIASP>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string HangSanXuat { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public string MoTa { get; set; }
        public string HinhMinhHoa { get; set; }
        public string MaLoai { get; set; }
        public Nullable<int> SoLuongSP { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string KieuDang { get; set; }
    
        public virtual ICollection<CTDonHang> CTDonHangs { get; set; }
        public virtual ICollection<CTPHIEUNHAP> CTPHIEUNHAPs { get; set; }
        public virtual ICollection<DANHGIASP> DANHGIASPs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
    }
}
